// ─── LMS Type Definitions ────────────────────────────────────────────────────
// All types used across the Online Sessions LMS product.
// BACKEND SWAP: These interfaces mirror the database schema.
// When backend is ready, API responses should map 1:1 to these types.

export type TeacherStatus = 'pending' | 'approved' | 'suspended'
export type SessionStatus = 'scheduled' | 'live' | 'completed' | 'cancelled'
export type NoticeType = 'announcement' | 'pdf'

export interface Teacher {
  id: string
  name: string
  email: string
  phone: string
  bio: string
  status: TeacherStatus
  registeredAt: string        // ISO datetime
  assignedClassIds: string[]
}

export interface Editor {
  id: string
  name: string
  email: string
  createdAt: string           // ISO datetime
  createdByAdminId: string
}

export interface Product {
  id: string
  name: string
  description: string
  upfrontPrice: number
  installmentAmount: number   // per month
  installmentMonths: number
  isActive: boolean
  classIds: string[]
  createdAt: string
}

export interface LmsClass {
  id: string
  productId: string
  name: string
  description: string
  teacherId: string
  defaultDurationMinutes: number
  enrolledStudentIds: string[]
}

export interface LmsSession {
  id: string
  classId: string
  scheduledAt: string         // ISO datetime
  durationMinutes: number
  status: SessionStatus
  meetingLink: string
  recordingUrl?: string
  attendanceCount?: number
  actualDurationMinutes?: number
  changeNote?: string         // required when editing after creation, logged for audit
  createdAt: string
}

export interface Notice {
  id: string
  classId: string
  teacherId: string
  title: string
  content: string
  type: NoticeType
  fileName?: string           // display name only — actual file upload is backend concern
  createdAt: string
}

export interface StudentEnrollment {
  studentId: string
  classId: string
  enrolledAt: string
  demoExpiresAt?: string      // undefined = full access
}

export interface DemoOverride {
  studentId: string
  studentName: string
  studentEmail: string
  demoExpiresAt: string | null  // null = full access granted
  overriddenByAdminId?: string
  overriddenAt?: string
}

// ─── Payloads (sent to service layer / future API) ───────────────────────────

export interface RegisterTeacherPayload {
  name: string
  email: string
  password: string
  phone: string
  bio: string
}

export interface CreateEditorPayload {
  name: string
  email: string
  password: string
}

export interface CreateProductPayload {
  name: string
  description: string
  upfrontPrice: number
  installmentAmount: number
  installmentMonths: number
  isActive: boolean
}

export interface CreateSessionPayload {
  classId: string
  scheduledAt: string
  durationMinutes: number
  meetingLink?: string  // generated by backend/Zoom API, not entered by teacher
  notes?: string
}

export interface UpdateSessionPayload extends CreateSessionPayload {
  changeNote: string          // required on edit
}

export interface CreateNoticePayload {
  classId: string
  title: string
  content: string
  type: NoticeType
  fileName?: string
}

// ─── Enriched / joined shapes used by UI components ─────────────────────────

export interface SessionWithClass extends LmsSession {
  className: string
  teacherName: string
  productName: string
}

export interface ClassWithProduct extends LmsClass {
  productName: string
  teacherName: string
  nextSession?: LmsSession
}
